// Test delle regole delle squadre (teams, rosters) nell'emulatore Firestore.
// Uso (dalla cartella principale): npm i --no-save @firebase/rules-unit-testing@4 firebase@11, poi
//   npx firebase-tools emulators:exec --only firestore --project demo-teams "node tests/teams.rules.test.mjs"
import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { doc, setDoc, updateDoc, deleteDoc, getDoc, getDocs, addDoc, query, collection, where, writeBatch } from 'firebase/firestore';
import fs from 'fs';
const env = await initializeTestEnvironment({ projectId: 'demo-teams', firestore: { rules: fs.readFileSync(process.argv[2] || 'firestore.rules', 'utf8'), host: '127.0.0.1', port: 8089 } });
await env.withSecurityRulesDisabled(async c => {
  const db = c.firestore();
  for (const u of ['cap', 'other']) await setDoc(doc(db, 'members', u), { first: 'A', last: 'B', gender: 'M' });
  await setDoc(doc(db, 'roles', 'org'), { tour: true });
  await setDoc(doc(db, 'roles', 'cap'), { captain: true });
  await setDoc(doc(db, 'scorers', 'campo1@x.it'), { court: '1', tid: '' });
});
const cap = env.authenticatedContext('cap', { email_verified: true }).firestore();
const other = env.authenticatedContext('other', { email_verified: true }).firestore();
const org = env.authenticatedContext('org', { email_verified: true }).firestore();
const anon = env.unauthenticatedContext().firestore();
const sc = env.authenticatedContext('s1', { email: 'campo1@x.it' }).firestore();
const team = { name: 'Fenicotteri', level: 'MASTER', kind: 'X', captainUid: 'cap', captainName: 'B A', status: 'pending', created: 1, updated: 1 };
let ok = 0, ko = 0;
const t = async (name, p) => { try { await p; ok++; console.log('✔', name); } catch (e) { ko++; console.log('✘', name, e.message.slice(0, 120)); } };
const batchSave = (db, id, tm, players, upd) => { const b = writeBatch(db); upd ? b.update(doc(db, 'teams', id), tm) : b.set(doc(db, 'teams', id), tm); b.set(doc(db, 'rosters', id), { captainUid: 'cap', players, updated: 2 }); return b.commit(); };
// admin principali per email (manofuori@gmail.com, pierpaolomurgioni@gmail.com): serve l'email confermata (col link o a mano: verified/{uid})
const pp = env.authenticatedContext('pp', { email: 'ManoFuori@gmail.com', email_verified: false }).firestore();
await t('email admin non confermata: non è admin', assertFails(getDoc(doc(pp, 'admins', 'probe'))));
await env.withSecurityRulesDisabled(c => setDoc(doc(c.firestore(), 'verified', 'pp'), { by: 'admin', at: 1 }));
await t('email admin confermata a mano: è admin', assertSucceeds(getDoc(doc(pp, 'admins', 'probe'))));
const fake = env.authenticatedContext('fake', { email: 'altro@x.it', email_verified: true }).firestore();
await t('altra email confermata: non è admin', assertFails(getDoc(doc(fake, 'admins', 'probe'))));
await t('admin tornei iscrive una squadra già ammessa, senza capitano nell\'app', assertSucceeds((() => { const b = writeBatch(org); b.set(doc(org, 'teams', 'ta'), { ...team, captainUid: '', captainName: 'Luca Bianchi', status: 'ok' }); b.set(doc(org, 'rosters', 'ta'), { captainUid: '', players: [{ num: 5, last: 'Bianchi', first: 'Luca', g: 'M', uid: '' }], updated: 1 }); return b.commit(); })()));
// l'admin generale corregge il nome di un utente (anche come capitano delle sue squadre); nessun altro può
const adm = env.authenticatedContext('Q0EvxfRr7wfZqvNeqLnRcSMN8Tv2', { email_verified: true }).firestore();
await t('admin corregge nome e cognome di un utente', assertSucceeds(updateDoc(doc(adm, 'members', 'other'), { first: 'Anna Maria', last: 'Rossi', gender: 'F' })));
await t('admin: nome vuoto rifiutato', assertFails(updateDoc(doc(adm, 'members', 'other'), { first: '' })));
await t('utente non cambia il nome di un altro', assertFails(updateDoc(doc(cap, 'members', 'other'), { first: 'X' })));
// altri admin generali (admins/{uid}), nominati da un admin generale
const oth = env.authenticatedContext('other', { email_verified: true }).firestore();
await t('utente normale non si nomina admin', assertFails(setDoc(doc(oth, 'admins', 'other'), { name: 'X', by: 'other', at: 1 })));
await t('utente normale non è admin', assertFails(getDoc(doc(oth, 'admins', 'probe'))));
await t('admin generale nomina un altro admin', assertSucceeds(setDoc(doc(adm, 'admins', 'other'), { name: 'Anna Maria Rossi', by: 'Q0EvxfRr7wfZqvNeqLnRcSMN8Tv2', at: 1 })));
await t('il nuovo admin è admin generale', assertSucceeds(getDoc(doc(oth, 'admins', 'probe'))));
await t('il nuovo admin vede l\'elenco degli admin', assertSucceeds(getDocs(collection(oth, 'admins'))));
await t('un admin non toglie se stesso', assertFails(deleteDoc(doc(oth, 'admins', 'other'))));
await t('un admin (non principale) nomina un altro admin', assertSucceeds(setDoc(doc(oth, 'admins', 'cap'), { name: 'Capitano', by: 'other', at: 2 })));
await t('un admin (non principale) non toglie un altro admin', assertFails(deleteDoc(doc(oth, 'admins', 'cap'))));
await t('l\'admin principale toglie quell\'admin', assertSucceeds(deleteDoc(doc(adm, 'admins', 'cap'))));
await t('l\'admin principale per email (confermato) toglie un admin', assertSucceeds(setDoc(doc(adm, 'admins', 'cap'), { name: 'C', by: 'x', at: 3 }).then(() => deleteDoc(doc(pp, 'admins', 'cap')))));
await t('nessuno toglie l\'admin principale (non è nella raccolta: resta admin)', assertSucceeds(deleteDoc(doc(oth, 'admins', 'Q0EvxfRr7wfZqvNeqLnRcSMN8Tv2')).catch(() => 0).then(() => getDoc(doc(adm, 'admins', 'probe')))));
const pm = env.authenticatedContext('pm', { email: 'pierpaolomurgioni@gmail.com', email_verified: true }).firestore();
await t('pierpaolomurgioni (confermato) è admin principale', assertSucceeds(getDoc(doc(pm, 'admins', 'probe'))));
await t('pierpaolomurgioni toglie un admin', assertSucceeds(setDoc(doc(adm, 'admins', 'cap'), { name: 'C', by: 'x', at: 4 }).then(() => deleteDoc(doc(pm, 'admins', 'cap')))));
await t('l\'admin principale toglie un admin', assertSucceeds(deleteDoc(doc(adm, 'admins', 'other'))));
await t('tolto: non è più admin', assertFails(getDoc(doc(oth, 'admins', 'probe'))));
await t('capitano crea squadra in attesa con rosa', assertSucceeds(batchSave(cap, 't1', team, [{ num: 7, last: 'R', first: 'M', g: 'M' }])));
await t('utente registrato non abilitato come capitano: niente iscrizione', assertFails(setDoc(doc(other, 'teams', 't6'), { ...team, captainUid: 'other' })));
await t('capitano non crea squadra già ammessa', assertFails(setDoc(doc(cap, 'teams', 't2'), { ...team, status: 'ok' })));
await t('non si crea squadra per un altro capitano', assertFails(setDoc(doc(other, 'teams', 't3'), team)));
await t('email non confermata: niente iscrizione', assertFails(setDoc(doc(env.authenticatedContext('other', { email_verified: false }).firestore(), 'teams', 't4'), { ...team, captainUid: 'other' })));
await t('tutti leggono le squadre', assertSucceeds(getDoc(doc(anon, 'teams', 't1'))));
await t('altri non leggono la rosa', assertFails(getDoc(doc(other, 'rosters', 't1'))));
await t('anonimo non legge la rosa', assertFails(getDoc(doc(anon, 'rosters', 't1'))));
await t('capitano legge le sue rose (query)', assertSucceeds(getDocs(query(collection(cap, 'rosters'), where('captainUid', '==', 'cap')))));
await t('scorer legge la rosa (referto)', assertSucceeds(getDoc(doc(sc, 'rosters', 't1'))));
await t('capitano collega i giocatori agli account (memberUids)', assertSucceeds(updateDoc(doc(cap, 'teams', 't1'), { memberUids: ['other'], updated: 2 })));
await t('admin tornei manda un avviso a un giocatore', assertSucceeds(addDoc(collection(org, 'notices'), { to: 'other', text: 'Gara spostata', at: 1, by: 'org' })));
await t('utente non manda avvisi ad altri utenti', assertFails(addDoc(collection(other, 'notices'), { to: 'cap', text: 'x', at: 1, by: 'other' })));
await t('capitano cambia livello in attesa', assertSucceeds(updateDoc(doc(cap, 'teams', 't1'), { level: 'DINOS', updated: 3 })));
await t('capitano non si auto-ammette', assertFails(updateDoc(doc(cap, 'teams', 't1'), { status: 'ok' })));
await t('altri non modificano la rosa', assertFails(setDoc(doc(other, 'rosters', 't1'), { captainUid: 'other', players: [], updated: 3 })));
await t('admin tornei ammette la squadra', assertSucceeds(updateDoc(doc(org, 'teams', 't1'), { status: 'ok', updated: 4 })));
await t('admin tornei legge la rosa', assertSucceeds(getDoc(doc(org, 'rosters', 't1'))));
await t('ammessa: capitano non cambia livello', assertFails(updateDoc(doc(cap, 'teams', 't1'), { level: 'SUPER 10', updated: 5 })));
await t('ammessa: capitano cambia nome e rosa', assertSucceeds(batchSave(cap, 't1', { name: 'Fenicotteri Rosa', level: 'DINOS', kind: 'X', captainUid: 'cap', updated: 6 }, [{ num: 1, last: 'X', first: 'Y', g: 'F' }], true)));
await t('ammessa: capitano non la ritira', assertFails(deleteDoc(doc(cap, 'teams', 't1'))));
await t('admin tornei elimina squadra e rosa', assertSucceeds((() => { const b = writeBatch(org); b.delete(doc(org, 'rosters', 't1')); b.delete(doc(org, 'teams', 't1')); return b.commit(); })()));
await t('capitano crea e ritira in attesa', assertSucceeds((async () => { await batchSave(cap, 't5', team, []); const b = writeBatch(cap); b.delete(doc(cap, 'rosters', 't5')); b.delete(doc(cap, 'teams', 't5')); await b.commit(); })()));
console.log(`\n${ok} ok, ${ko} falliti`);
await env.cleanup();
process.exit(ko ? 1 : 0);
